// Single source of truth for custom role permission nodes
export const Permissions = {
  VIEW_PENDING_QUEUE: 'VIEW_PENDING_QUEUE',
  APPROVE_REJECT_BOOKINGS: 'APPROVE_REJECT_BOOKINGS',
  BOOKING_OVERRIDE: 'BOOKING_OVERRIDE',
  MANAGE_ROOMS: 'MANAGE_ROOMS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  VIEW_ANALYTICS_DASHBOARD: 'VIEW_ANALYTICS_DASHBOARD',
  EXPORT_AUDIT_LOGS: 'EXPORT_AUDIT_LOGS',
  ISSUE_BAN: 'ISSUE_BAN'
} as const;

export type PermissionType = typeof Permissions[keyof typeof Permissions];
